/**
 * Shortcodes Pro Admin JS
 *
 * @package  Shortcodes Pro
 * @author   Matt Varone
*/
var mv_shortcodespro_js_params;jQuery(function(){var m=".shortcodespro-meta-box ",k=[],l=m+"#type",o=m+"#attributes",u="#attributes-values",q=m+".sscattributes",h=m+"#language",i=m+"#button",e="#postimagediv";
jQuery("#post_title").focus();jQuery(l+" option").each(function(){k.push(jQuery(this).prop("value"));});jQuery(l).on("change",function(){var v=jQuery(this).prop("value");
r(v);});r(jQuery(l).prop("value"));jQuery(o).on("change",function(){n();});n();jQuery(h).on("change",function(){var v=jQuery(o).prop("checked");if(v===true){t(true);
}else{t();}});s();g();jQuery("#button").on("change",function(){g();});jQuery(".add_attribute").live("click",function(){var v=jQuery("#att_name").val(),x=jQuery("#att_label").val(),B=jQuery("#att_desc").val(),y=jQuery("#att_type").val(),A=jQuery("#att_value").val(),w=jQuery("#att_options").val();
if(v.length<1||x.length<1||y.length<1||A.length<1){b();return false;}if(y==="select"&&w.length<1){b();return false;}v=f(v);var z=new d(v,x,B,y,A,w);if(jQuery("#att_slug_"+v).length>0){tb_remove();
return false;}else{a(z);s();tb_remove();}});jQuery(".update_attribute").live("click",function(){var y=jQuery(this).prop("id").replace("att_",""),x=y,B=jQuery("#att_label").val(),z=jQuery("#att_desc").val(),A=jQuery("#att_type").val(),C=jQuery("#att_value").val(),w=jQuery("#att_order_"+y).val(),D=jQuery("#att_options").val();
if(B.length<1||A.length<1||C.length<1){b();return false;}if(A==="select"&&D.length<1){b();return false;}var v=new d(x,B,z,A,C,D);c(v,"#row_"+y,w);tb_remove();
});jQuery(".button.delete").live("click",function(){var z=confirm(mv_shortcodespro_js_params.in_delete_confirmation);if(z){var A=jQuery(this).parent().parent(),w=A.prop("id").replace("row_",""),v=jQuery("#attrvals").val(),x=v.replace("|%"+w+"%","");
jQuery("#attrvals").val(x);var y=jQuery("#totalattr").val(),B=parseFloat(y)-1;jQuery("#totalattr").val(B);A.remove();s();}else{return false;}});jQuery("#att_type").live("change",function(){var v=jQuery(this).val();
p(v);});function r(v){if(v!=="insert-custom-code"){jQuery(u).hide();jQuery(".sscquicktag").show();jQuery(q).stop().fadeTo(50,0.5,function(){jQuery(o).removeAttr("checked").prop("disabled","disabled");
jQuery(".sscdesclong,.sscwidth,.sscheight").hide();});}else{jQuery(".sscquicktag").hide();jQuery(q).stop().fadeTo(50,1,function(){jQuery(o).removeAttr("disabled");
});}jQuery.each(k,function(w,x){if(x===v){jQuery("#"+x).show();}else{jQuery("#"+x).hide();}});}function j(v,x){var w=""+v;while(w.length<x){w="0"+w;}return w;
}function n(){var v=jQuery(o).prop("checked");if(v===true){jQuery(u).show();if(jQuery("#button").is(":checked")){jQuery(".sscdesclong,.sscwidth,.sscheight").show();
}t(true);}else{jQuery(u).hide();jQuery(".sscdesclong,.sscwidth,.sscheight").hide();t();}}function t(w){var v=jQuery(h).prop("value");switch(v){case"php":jQuery(".sscinsert-php").show();
jQuery(".sscinsert-css,.sscinsert-html").hide();if(jQuery("#button").is(":checked")){jQuery(".sscexecute").show();}break;case"html":jQuery(".sscinsert-html").show();
jQuery(".sscinsert-css,.sscinsert-php").hide();if(jQuery("#button").is(":checked")){jQuery(".sscexecute").show();}break;case"css":jQuery(".sscinsert-css").show();
jQuery(".sscinsert-html,.sscinsert-php").hide();jQuery(".sscexecute").prop("checked","").hide();break;}if(w===true){jQuery(m+".attributes-desc").show();
}else{jQuery(m+".attributes-desc").hide();}}function s(){var w=jQuery(".scp-attributes-header"),v=jQuery("#totalattr").val();if(v>0){w.show();}else{w.hide();
}}function g(){var v=".sscexecute,.sscprevent,.sscrowbutton,.sscdesc",w=v+",.sscdesc,.sscdesclong,.sscwidth,.sscheight";if(jQuery("#button").is(":checked")){if(jQuery("#attributes").is(":checked")){jQuery(w).show();
}else{jQuery(v).show();}}else{jQuery(w).hide();}}function p(v){if(v==="select"){jQuery(".sscatt_options").show();}else{jQuery(".sscatt_options").hide();
}}function d(v,x,A,y,z,w){this.slug=v;this.label=x;this.desc=A;this.type=y;this.value=z;this.options=w;}function a(A){var x=jQuery("#attrvals").val(),z=jQuery("#totalattr").val(),y=jQuery("#lastattr").val(),C=parseFloat(z)+1,v=parseFloat(y)+1,B='<input type="hidden" name="att_desc_'+A.slug+'" value="'+A.desc+'" id="att_desc_'+A.slug+'"/><input type="hidden" name="att_type_'+A.slug+'" value="'+A.type+'" id="att_type_'+A.slug+'"/><input type="hidden" name="att_value_'+A.slug+'" value="'+A.value+'" id="att_value_'+A.slug+'"/><input type="hidden" name="att_options_'+A.slug+'" value="'+A.options+'" id="att_options_'+A.slug+'"/>',w='<tr class="sscrow" id="row_'+A.slug+'"><td width="25%"><input type="text" name="att_order_'+A.slug+'" id="att_order_'+A.slug+'" value="'+v+'" size="4" ></td><td width="25%"><input type="text" name="att_slug_'+A.slug+'" id="att_slug_'+A.slug+'" value="'+A.slug+'"readonly="readonly"></td><td width="25%"><input type="text" name="att_label_'+A.slug+'" id="att_label_'+A.slug+'" value="'+A.label+'"readonly="readonly"></td><td width="25%"><a class="edit button thickbox" href="admin-ajax.php?action=scpeditattribute&width=640&id='+A.slug+'">'+mv_shortcodespro_js_params.in_edit+'</a> <a class="delete button" href="#">'+mv_shortcodespro_js_params.in_delete+"</a>"+B+"</td></tr>";
jQuery(".sscadd-new-attributed").before(w);jQuery("#totalattr").val(C);jQuery("#lastattr").val(v);jQuery("#attrvals").val(x+"|%"+A.slug+"%");}function c(x,z,v){var y='<input type="hidden" name="att_desc_'+x.slug+'" value="'+x.desc+'" id="att_desc_'+x.slug+'"/><input type="hidden" name="att_type_'+x.slug+'" value="'+x.type+'" id="att_type_'+x.slug+'"/><input type="hidden" name="att_value_'+x.slug+'" value="'+x.value+'" id="att_value_'+x.slug+'"/><input type="hidden" name="att_options_'+x.slug+'" value="'+x.options+'" id="att_options_'+x.slug+'"/>',w='<tr class="sscrow" id="row_'+x.slug+'"><td width="25%"><input type="text" name="att_order_'+x.slug+'" id="att_order_'+x.slug+'" value="'+v+'" size="3"></td><td width="25%"><input type="text" name="att_slug_'+x.slug+'" id="att_slug_'+x.slug+'" value="'+x.slug+'"readonly="readonly"></td><td width="25%"><input type="text" name="att_label_'+x.slug+'" id="att_label_'+x.slug+'" value="'+x.label+'"readonly="readonly"></td><td width="25%"><a class="edit button thickbox" href="admin-ajax.php?action=scpeditattribute&width=640&id='+x.slug+'">'+mv_shortcodespro_js_params.in_edit+'</a> <a class="delete button" href="#">'+mv_shortcodespro_js_params.in_delete+"</a>"+y+"</td></tr>";
jQuery(z).replaceWith(w);}function b(){jQuery("#errors").text(mv_shortcodespro_js_params.in_validation_alert);}function f(x){x=x.replace(/^\s+|\s+$/g,"");
x=x.toLowerCase();var z="àáäâèéëêìíïîòóöôùúüûñç·/_,:;",y="aaaaeeeeiiiioooouuuunc------";for(var w=0,v=z.length;w<v;w++){x=x.replace(new RegExp(z.charAt(w),"g"),y.charAt(w));
}x=x.replace(/[^a-z0-9]/g,"").replace(/\s+/g,"").replace(/-+/g,"");return x;}});